### ISSUE TITLE
updateWhere … unset fails to repack array

### ISSUE THREAD

**Issue by david-bezero** [davidje13/json-immutability-helper#1]
```
console.log(update([1,2,3], ['updateWhere', [2], ['unset']]))
```

> [1, undefined, 3]

This operation should re-pack the array to `[1, 3]`.

The same applies with `['set', UNSET_TOKEN]`.

`deleteWhere` / `deleteFirstWhere` / etc., as well as `{1: ['unset']}`, all work as expected.

**Comment by davidje13** [comment]
Fixed in 458d93485526a1c31c6c3ed0187cf3bc5e4d7a99
